### ISSUE TITLE
[Bug] Discord bot does not respond to requests and the plugin gives an error

### ISSUE THREAD

**Issue by Elaronnd** [bivashy/MC-Auth-with-Link#149]
![image](https://github.com/bivashy/MC-Auth-with-Link/assets/155093098/028caf93-359a-4e1f-b49d-70359158b929)
Before this, I checked and the bot has administrator rights(Перед этим я проверил и у бота есть права администратора)
I also attached the server logs(Также прикрепил логи сервера)
[2024-01-28-7.log](https://github.com/bivashy/MC-Auth-with-Link/files/14075835/2024-01-28-7.log)

**Comment by bivashy** [comment]
Fill out issue template, and reopen the issue/ask it

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Launch '...'
2. Execute '....'
3. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.
